### ISSUE TITLE
Extract common schema script broken

### ISSUE THREAD

**Issue by wolfy1339** [octokit/webhooks#573]
```
$ ./bin/extract-common-schema.ts DeploymentCreatedEvent.deployment Deployment
/home/user/Desktop/Programming/webhooks/bin/utils/misc.ts:10
  assert.ok(str, "unable to guess interface name");
         ^
AssertionError [ERR_ASSERTION]: unable to guess interface name
    at guessAtInterfaceName (/home/user/Desktop/Programming/webhooks/bin/utils/misc.ts:10:10)
    at /home/user/Desktop/Programming/webhooks/bin/utils/loadMapOfSchemas.ts:15:39
    at /home/user/Desktop/Programming/webhooks/bin/utils/forEachJsonFile.ts:14:5
    at Array.forEach (<anonymous>)
    at forEachJsonFile (/home/user/Desktop/Programming/webhooks/bin/utils/forEachJsonFile.ts:7:54)
    at loadMapOfSchemas (/home/user/Desktop/Programming/webhooks/bin/utils/loadMapOfSchemas.ts:10:18)
    at Object.<anonymous> (/home/user/Desktop/Programming/webhooks/bin/extract-common-schema.ts:80:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/user/Desktop/Programming/webhooks/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

```
$ node --version
v16.10.0
$ npm --version
6.14.15
```

**Comment by wolfy1339** [comment]
This seems to have resolved somewhat, It now only happens sporadically

**Comment by G-Rath** [comment]
Huh I didn't see this issue originally being created - that means we've got something that isn't following our standard naming conventions.

In the original error you posted, it's got `undefined` meaning a schema is missing (iirc) `title`.

**Comment by G-Rath** [comment]
@wolfy1339 let me know if you'd like me to look into this properly - it's not a really bug as I always expected the tool wouldn't always be able to guess at interface names, but it might be something we can improve.

**Comment by wolfy1339** [comment]
It should fallback to `$id` if `title` isn't present.

I made a simple script to check, and no schema is missing a `title` of `$id` property
<details>

```ts
#!/usr/bin/env ts-node-transpile-only

import { forEachJsonFile } from "./bin/utils";
import * as fs from "fs";

forEachJsonFile('payload-schemas/api.github.com/', (filePath) => {
  const contents = fs.readFileSync(filePath, "utf-8");
  const json = JSON.parse(contents);

  if (!json.title) {
    console.warn(`${filePath} is missing a title`);
    process.exitCode = 1;
  }
  if (!json.$id) {
    console.warn(`${filePath} is missing a ref`);
    process.exitCode = 1;
  }
});
```
</details>

No changes were made to schema title, or id, or new schemas when this issue was created.

**Comment by G-Rath** [comment]
@wolfy1339 do you have any reproductions on hand? It works fine for me running `./bin/extract-common-schema.ts DeploymentCreatedEvent.deployment Deployment` on `HEAD~1`.

**Comment by wolfy1339** [comment]
not recently

**Comment by G-Rath** [comment]
Given that, are you ok if we close this and we can re-open if you come across it again?

**Comment by wolfy1339** [comment]
That sounds good.
